BASE_CHEQUE_CHAT_ID = -1002211589355
BASE_CHEQUE_THREAD_ID = 53848

BASE_TRONSCAN_TRANSACTION_LINK = "https://tronscan.org/#/transaction/"
TECHNICAL_COMMAND_THREAD_CHAT_ID = 1
TECHNICAL_COMMAND_CHAT_ID = 1
